ls:
    .dir: PascalCase | regex:([A-Z][a-zA-Z0-9]*)(\.[A-Z][a-zA-Z0-9]*)*
    .ts: regex:([a-z][a-zA-Z0-9]*|[A-Z][a-zA-Z0-9]*)(\.[A-Z][a-zA-Z0-9]*)*

ignore: ['**/.git/**', '**/.github/**', '**/.config/**', '**/.vscode/**', '**/node_modules/**', '**/coverage/**', '**/reports/**', '**/out/**']
