name: Setup Project
description: Prepares the Node project from the github repository

inputs:
  repository-name:
    description: The name of the repository
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@main
      with:
        node-version: 24.13.0
    - name: Cache Npm Packages
      uses: actions/cache@main
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ inputs.repository-name }}-npm-packages-${{ hashFiles('package.json') }}
        restore-keys: ${{ runner.os }}-${{ inputs.repository-name }}-npm-packages-
    - name: Install Npm Packages
      run: npm install
      shell: bash
    - name: Build Project
      run: npm run build
      shell: bash
