name: Pull Request Changed

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: read
  pull-requests: read

jobs:
  is-spelling-valid:
    name: Is Spelling Valid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run Spell Check
        uses: streetsidesoftware/cspell-action@3dfff3f708988a84f16802c20979fe0556342aeb
        with:
          check_dot_files: true
          incremental_files_only: false

  is-code-valid:
    name: Is Code Valid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Setup Project
        uses: ./.github/actions/SetupProject
        with:
          repository-name: ${{ github.event.repository.name }}
      - name: Run Prettier
        run: npx prettier . --check
      - name: Run Lint
        run: npm run lint
      - name: Install EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Run EditorConfig Checker
        run: editorconfig-checker
      - name: Run LsLint
        uses: ls-lint/action@main
        with:
          config: .ls-lint.yaml

  is-ci-valid:
    name: Is CI Valid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Run Actionlint
        run: brew install actionlint && actionlint
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          quiet: true
      - name: Run KICS
        uses: Checkmarx/kics-github-action@master
        with:
          path: ./

  is-code-secure:
    name: Is Code Secure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Setup Project
        uses: ./.github/actions/SetupProject
        with:
          repository-name: ${{ github.event.repository.name }}
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Run Syft Create SBOM
        uses: anchore/sbom-action@main
        with:
          format: spdx-json
          output-file: explorer-sorter-sbom.spdx.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Grype Check SBOM
        uses: anchore/scan-action@main
        with:
          sbom: ./explorer-sorter-sbom.spdx.json
          output-format: table
      - name: Run Grype Scan
        uses: anchore/scan-action@main
        with:
          path: ./
          output-format: table
      - name: Run TruffleHog OSS
        run: brew install trufflehog && trufflehog git file://./ --fail
      - name: Run Secretlint
        run: npx @secretlint/quick-start "**/*"
      - name: Run Gitleaks
        run: brew install gitleaks && gitleaks detect --redact --verbose --no-git
      - name: Run Trivy
        run: brew install trivy && trivy fs --scanners vuln,misconfig,secret,license --license-full --ignored-licenses MIT --exit-code 1 ./

  is-documentation-valid:
    name: Is Documentation Valid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: 24.13.0
      - name: Run Spell Check
        run: npm install && npx cspell . --no-progress
      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@main
        with:
          globs: "**/*.md"
      - name: Run Remark
        run: npx remark-cli .
      - name: Run Markdown Link Check
        run: find . -name \*.md -print0 | xargs -0 -n1 npx markdown-link-check -c .markdownlinkcheck.json
      - name: Run Markdown Table Formatter
        run: npx markdown-table-formatter --check "**/*.md"
